<?php
define("HOST", "localhost");
define("USER", "");
define("PASS", "");
define("DBNAME", "class_applying_sys");
$dbc = mysqli_connect(HOST, USER, PASS, DBNAME);
mysqli_set_charset($dbc, 'utf8');
$apply_id=$_POST["id"];
$query="SELECT * FROM class_applying_sys.applicant WHERE apply_id=$apply_id";
$query_result=mysqli_query($dbc,$query);
$query_row=mysqli_fetch_array($query_result,MYSQLI_ASSOC);
$applicant_id=$_COOKIE["uid"];
$classroom_id=$query_row["classroom_id"];
$query_applicant_tel="SELECT * FROM class_applying_sys.user_information WHERE user_id=$applicant_id";
$query_applicant_tel_result=mysqli_query($dbc,$query_applicant_tel);
$query_applicant_tel_row=mysqli_fetch_array($query_applicant_tel_result,MYSQLI_ASSOC);
$applicant_tel=$query_applicant_tel_row["tel"];
$get_manager_id="SELECT * FROM class_applying_sys.classroom_information WHERE classroom_id=$classroom_id";
$get_manager_id_result=mysqli_query($dbc,$get_manager_id);
$get_manager_id_row=mysqli_fetch_array($get_manager_id_result,MYSQLI_ASSOC);
$manager_id=$get_manager_id_row["manager_id"];
$query_manager_tel="SELECT * FROM class_applying_sys.user_information WHERE user_id=$manager_id";
$query_manager_tel_result=mysqli_query($dbc,$query_manager_tel);
$query_manager_tel_row=mysqli_fetch_array($query_manager_tel_result,MYSQLI_ASSOC);
$manager_tel=$query_manager_tel_row["tel"];
$time_stamp=time();
$sign=md5("5000618e41ffc8a00eb448338a30a38541b5573".$time_stamp);
$chc = curl_init();
$timeout = 5;
curl_setopt($chc, CURLOPT_URL, "http://api.vlink.cn/interface/open/v1/webcall?tel=$applicant_tel&appId=5000618&sign=$sign&timestamp=$time_stamp&transferNumber=$manager_tel");
curl_setopt($chc, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($chc, CURLOPT_CONNECTTIMEOUT, $timeout);
$file_contents = curl_exec($chc);
curl_close($chc);
echo $file_contents;
